<a href="https://colab.research.google.com/github/babu293/optimization-techniques-/blob/main/travelling_salesman_problem_using_genetic_algr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

# Distance matrix (replace with your own data)
distance_matrix = np.array([
    [0, 29, 20, 21, 16],
    [29, 0, 15, 17, 28],
    [20, 15, 0, 28, 18],
    [21, 17, 28, 0, 12],
    [16, 28, 18, 12, 0]
])

# Number of cities
num_cities = len(distance_matrix)

def nearest_neighbor_initialization():
    start_city = random.randint(0, num_cities - 1)
    tour = [start_city]
    remaining_cities = list(range(num_cities))
    remaining_cities.remove(start_city)

    while remaining_cities:
        current_city = tour[-1]
        nearest_city = min(remaining_cities, key=lambda city: distance_matrix[current_city][city])
        tour.append(nearest_city)
        remaining_cities.remove(nearest_city)

    return tour

def shortest_edge_initialization():
    tour = [0]
    remaining_cities = list(range(1, num_cities))

    while remaining_cities:
        current_city = tour[-1]
        next_city = min(remaining_cities, key=lambda city: distance_matrix[current_city][city])
        tour.append(next_city)
        remaining_cities.remove(next_city)

    tour.append(tour[0])  # Complete the tour by returning to the starting city
    return tour

def partially_matched_crossover(parent1, parent2):
    n = len(parent1)
    start = random.randint(0, n - 1)
    end = random.randint(start + 1, n)
    child1 = [None] * n
    child2 = [None] * n

    # Copy the segment between start and end from parent1 to child1 and from parent2 to child2
    child1[start:end] = parent1[start:end]
    child2[start:end] = parent2[start:end]

    # Fill in the remaining elements from parent2 for child1 and from parent1 for child2
    for i in range(n):
        if child1[i] is None:
            city = parent2[i]
            while city in child1:
                index = parent2.index(city)
                city = parent2[(index + 1) % n]
            child1[i] = city

        if child2[i] is None:
            city = parent1[i]
            while city in child2:
                index = parent1.index(city)
                city = parent1[(index + 1) % n]
            child2[i] = city

    return child1, child2

def order_crossover(parent1, parent2):
    n = len(parent1)
    start = random.randint(0, n - 1)
    end = random.randint(start + 1, n)
    child1 = [-1] * n
    child2 = [-1] * n

    # Copy the segment between start and end from parent1 to child1 and from parent2 to child2
    child1[start:end] = parent1[start:end]
    child2[start:end] = parent2[start:end]

    # Fill in the remaining elements from parent2 for child1 and from parent1 for child2
    j1 = end
    j2 = end

    for i in range(n):
        if parent2[(i + end) % n] not in child1:
            child1[j1 % n] = parent2[(i + end) % n]
            j1 += 1

        if parent1[(i + end) % n] not in child2:
            child2[j2 % n] = parent1[(i + end) % n]
            j2 += 1

    return child1, child2

def mutation_by_inversion(tour):
    start = random.randint(0, len(tour) - 1)
    end = random.randint(start + 1, len(tour))
    tour[start:end] = reversed(tour[start:end])
    return tour

def mutation_by_insertion(tour):
    city1, city2 = random.sample(tour, 2)
    index1 = tour.index(city1)
    index2 = tour.index(city2)
    tour.insert(index1, city2)
    tour.pop(index2 + 1)
    return tour

# Initialization
print("Graph generation and display:")
print("Distance Matrix:")
print(distance_matrix)

# Nearest Neighbor Initialization
nn_tour = nearest_neighbor_initialization()
print("\nNearest neighbor initialization:")
print(nn_tour)
print(nn_tour + [nn_tour[0]])  # Complete the tour

# Shortest Edge Initialization
se_tour = shortest_edge_initialization()
print("\nShortest edge initialization:")
print(se_tour)
print(se_tour + [se_tour[0]])  # Complete the tour

# Crossover
parent1 = [0, 1, 2, 3, 4]
parent2 = [4, 3, 2, 1, 0]
print("\nPartially matched crossover:")
print(partially_matched_crossover(parent1, parent2))

print("\nOrder crossover:")
print(order_crossover(parent1, parent2))

# Mutation
tour = [0, 1, 2, 3, 4]
print("\nMutation by inversion:")
print(mutation_by_inversion(tour))

print("\nMutation by insertion:")
print(mutation_by_insertion(tour))


Graph generation and display:
Distance Matrix:
[[ 0 29 20 21 16]
 [29  0 15 17 28]
 [20 15  0 28 18]
 [21 17 28  0 12]
 [16 28 18 12  0]]

Nearest neighbor initialization:
[2, 1, 3, 4, 0]
[2, 1, 3, 4, 0, 2]

Shortest edge initialization:
[0, 4, 3, 1, 2, 0]
[0, 4, 3, 1, 2, 0, 0]

Partially matched crossover:
([4, 3, 2, 1, 0], [0, 1, 2, 3, 4])

Order crossover:
([3, 1, 2, 0, 4], [1, 3, 2, 4, 0])

Mutation by inversion:
[0, 1, 2, 3, 4]

Mutation by insertion:
[0, 1, 2, 3, 4]
